version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - volume:/data/db
volumes:
  volume: